In [84]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [85]:
df = pd.read_excel("fake_panel.xlsx")

In [86]:
df.columns = ["country", "year", "gdp", "defence", "health", "sport", "education"]

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   country    270 non-null    object 
 1   year       270 non-null    int64  
 2   gdp        270 non-null    float64
 3   defence    270 non-null    float64
 4   health     270 non-null    float64
 5   sport      270 non-null    float64
 6   education  270 non-null    float64
dtypes: float64(5), int64(1), object(1)
memory usage: 14.9+ KB


In [88]:
df["gdp"].mean()

2.692

In [89]:
df["defence"].mean()

1.2433333333333334

In [90]:
df["health"].mean()

6.402962962962964

In [91]:
df["sport"].mean()

0.3877777777777777

In [92]:
df["education"].mean()

4.934814814814815

In [93]:
df["gdp"].autocorr()

-0.03978762506455344

In [94]:
df["defence"].autocorr()

0.7493858687716618

In [95]:
df["health"].autocorr()

0.8743926904226766

In [96]:
df["sport"].autocorr()

0.8522645932284458

In [97]:
df["education"].autocorr()

0.8858123400768985

In [98]:
df["gdp"].describe()

count    270.000000
mean       2.692000
std        3.849976
min      -10.940000
25%        1.242500
50%        2.575000
75%        4.367500
max       24.620000
Name: gdp, dtype: float64

In [99]:
df["gdp"].kurtosis()

5.273021107883682

In [100]:
X = df[["defence", "health", "sport", "education"]]
y = df["gdp"]

In [101]:
regression = linear_model.LinearRegression()
regression.fit(X, y)

LinearRegression()

In [102]:
regression.get_params(deep=True)

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False}

In [122]:
regression.score(X, y)

0.12678349088145913

In [103]:
regression.coef_

array([-1.29256698, -0.6610207 , -2.52752311, -0.12582597])

In [104]:
regression.predict([[1.0, 6.40, 0.39, 4.93]])

C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([3.00347232])

In [105]:
regression.predict([[2.0, 6.40, 0.39, 4.93]])

C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1.71090534])

In [106]:
regression.predict([[3.0, 6.40, 0.39, 4.93]])

C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.41833837])

In [107]:
regression.predict([[4.0, 6.40, 0.39, 4.93]])

C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-0.87422861])

In [108]:
regression.predict([[5.0, 6.40, 0.39, 4.93]])

C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-2.16679559])

In [109]:
from scipy import stats

In [120]:
#slope, intercept, r, p, std_err = stats.linregress(df["defence"], y)
#result = stats.linregress(df["defence"], y)
#result = stats.linregress(df["health"], y)
#result = stats.linregress(df["sport"], y)
result = stats.linregress(df["education"], y)

In [121]:
print(result.slope)
print(result.pvalue)
print(result.intercept)
print(result.rvalue * result.rvalue)
print(result.stderr)
#The Pearson correlation coefficient. The square of rvalue is equal to the coefficient of determination.

-0.7981742385842513
0.0007573759397455776
6.630842057369098
0.04151652057217524
0.23426755828633955
